# Generated by Django 3.1.2 on 2020-11-03 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 11, 3, 3, 18, 32, 536571))),
            ],
        ),
    ]
