# Generated by Django 3.1.2 on 2020-11-20 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201113_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='time_asked',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_asked',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
