# Generated by Django 3.1.2 on 2020-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201120_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='anonymous', max_length=10000),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='anonymous', max_length=10000),
        ),
    ]
